// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportApp.Data;

#nullable disable

namespace ReportApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213112156_SeedVentas")]
    partial class SeedVentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2");

            modelBuilder.Entity("ReportApp.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Producto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fecha = new DateTime(2026, 2, 11, 5, 21, 55, 928, DateTimeKind.Local).AddTicks(7769),
                            Monto = 25000m,
                            Producto = "Laptop Gamer"
                        },
                        new
                        {
                            Id = 2,
                            Fecha = new DateTime(2026, 2, 12, 5, 21, 55, 928, DateTimeKind.Local).AddTicks(7787),
                            Monto = 800m,
                            Producto = "Mouse Inalámbrico"
                        },
                        new
                        {
                            Id = 3,
                            Fecha = new DateTime(2026, 2, 13, 5, 21, 55, 928, DateTimeKind.Local).AddTicks(7789),
                            Monto = 7000m,
                            Producto = "Monitor 4K"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
